// <auto-generated />
using System;
using CheckPoint.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CheckPoint.Api.Migrations
{
    [DbContext(typeof(CheckPointDbContext))]
    [Migration("20260911153905_AddFeedbackRequest")]
    partial class AddFeedbackRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CheckPoint.Api.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.FeedbackRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectMembershipId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectMembershipId");

                    b.ToTable("FeedbackRequests");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.MagicLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeedbackRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("MagicLinks");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("HeadOfPracticeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LineManagerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeadOfPracticeId");

                    b.HasIndex("LineManagerId");

                    b.HasIndex("PracticeId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.Poc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectMembershipId")
                        .HasColumnType("uuid");

                    b.Property<int>("Relationship")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectMembershipId");

                    b.ToTable("Pocs");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.Practice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PracticeLeadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PracticeLeadId");

                    b.ToTable("Practices");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.ProjectMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMemberships");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Practice Lead"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Line Manager"
                        });
                });

            modelBuilder.Entity("PersonRole", b =>
                {
                    b.Property<Guid>("PeopleId")
                        .HasColumnType("uuid");

                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.HasKey("PeopleId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PersonRole");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.FeedbackRequest", b =>
                {
                    b.HasOne("CheckPoint.Api.Domain.ProjectMembership", "ProjectMembership")
                        .WithMany()
                        .HasForeignKey("ProjectMembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectMembership");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.Person", b =>
                {
                    b.HasOne("CheckPoint.Api.Domain.Person", "HeadOfPractice")
                        .WithMany()
                        .HasForeignKey("HeadOfPracticeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CheckPoint.Api.Domain.Person", "LineManager")
                        .WithMany()
                        .HasForeignKey("LineManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CheckPoint.Api.Domain.Practice", "Practice")
                        .WithMany("People")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HeadOfPractice");

                    b.Navigation("LineManager");

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.Poc", b =>
                {
                    b.HasOne("CheckPoint.Api.Domain.ProjectMembership", "ProjectMembership")
                        .WithMany("Pocs")
                        .HasForeignKey("ProjectMembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectMembership");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.Practice", b =>
                {
                    b.HasOne("CheckPoint.Api.Domain.Department", "Department")
                        .WithMany("Practices")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheckPoint.Api.Domain.Person", "PracticeLead")
                        .WithMany()
                        .HasForeignKey("PracticeLeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("PracticeLead");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.ProjectMembership", b =>
                {
                    b.HasOne("CheckPoint.Api.Domain.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CheckPoint.Api.Domain.Project", "Project")
                        .WithMany("Memberships")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PersonRole", b =>
                {
                    b.HasOne("CheckPoint.Api.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheckPoint.Api.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.Department", b =>
                {
                    b.Navigation("Practices");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.Practice", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.Project", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("CheckPoint.Api.Domain.ProjectMembership", b =>
                {
                    b.Navigation("Pocs");
                });
#pragma warning restore 612, 618
        }
    }
}
